<?php

/**
 * @file
 *  A client for the GottaGo module.
 */

/**
 * Implements hook_menu().
 */
function gottago_client_menu() {
  $items['gottago_client/%'] = array(
    'title' => 'GottaGo Client',
    'access callback' => TRUE,
    'page callback' => 'gottago_client_page',
    'type' => MENU_CALLBACK,
  );
  return $items;
}

function gottago_client_page_delivery_callback_alter(&$delivery_callback) {
  if (arg(0) == 'gottago_client') {
    $delivery_callback = 'gottago_client_delivery_page';
  }
  drupal_add_js(drupal_get_path('module', 'gottago_client') . '/statusquery.js');
  drupal_add_js(drupal_get_path('module', 'gottago_client') . '/gottago_client.js');
}

function gottago_client_page() {

}

/**
 * Implements hook_init().
 */
function gottago_client_init() {
  drupal_add_js(drupal_get_path('module', 'gottago_client') . '/statusquery.js');
  drupal_add_js(drupal_get_path('module', 'gottago_client') . '/gottago_client.js');
}

function gottago_client_delivery_page($page_callback_result) {
  $css = '<style type="text/css">
            .status_indicator {
                display:none;
                font-size: 5em;
                background: #eee;
                border: 1px solid #666;
                padding:0.25em;
                margin: 1em;
            }
            .status_indicator.error {
                 background: red;
            }
            .status_indicator.off {}
            .status_indicator.go {
                background:lightgreen;
            }
            .status_indicator.no_go {
                background:lightcoral;
            }
        </style>';
  $js = drupal_get_js();
  $output = '<html>
              <head>
                <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
                '. $css . $js . '
              </head>
              <body>
                <div class="status_indicator" rel="'.arg(1).'"></div>
              </body>
            </html>';
  print $output;
  /*echo '<pre>';

  print_r($js);
  $html = theme('html');
  print_r($page_callback_result); die();*/
}